### ISSUE TITLE
Continuing with the Prototype.

### ISSUE THREAD

**Issue by HatchyHatch14** [UoSGamesGroups/level-6-l6-group-10#4]
Continue to build up the Prototype, Using notes from Chris's meeting look into file formats like JSON.

Create different scripts for the the rhythm attacks after mastering the simple code first.

Feel free to use any sort out placement art for now, as that will come in later.

**Comment by DeepRiverIndigo** [comment]
I have done 4 hours of scripting, 1 hour and a half of researching into Json and Queue(T).
