### ISSUE TITLE
Research, Play Frets of Fire.

### ISSUE THREAD

**Issue by HatchyHatch14** [UoSGamesGroups/level-6-l6-group-10#5]
As Chris suggested, Frets of Fire is a game that is similar to our mechanics. 

So for research we are going to play it for a bit and see how well it works as a Rhythm game, be sure to record anything useful or interesting down in a research document. 

(30 minutes should be plenty)

**Comment by DeepRiverIndigo** [comment]
Played through half an hour of Frets of Fire as suggested by Chris Janes during our pitch meeting.
